import http from "http";
import { exec } from "child_process";
import { randomUUID } from "crypto";

const API = "https://api.spotify.com/v1";
const AUTH = "https://accounts.spotify.com";

const openBrowser = (url) => {
  const cmd = { darwin: "open", win32: "start" }[process.platform] ?? "xdg-open";
  exec(`${cmd} "${url}"`, () => {}); // best-effort; URL is always printed to console
};

const basicAuth = (clientId, clientSecret) =>
  Buffer.from(`${clientId}:${clientSecret}`).toString("base64");

/**
 * Run the Spotify Authorization Code OAuth flow.
 * Starts a one-shot local HTTP server to capture the callback, opens the
 * browser, and resolves with the access + refresh tokens.
 */
export const authenticate = (clientId, clientSecret, redirectUri) =>
  new Promise((resolve, reject) => {
    const state = randomUUID();
    const port = Number(new URL(redirectUri).port) || 3000;

    const server = http.createServer(async (req, res) => {
      const url = new URL(req.url, `http://localhost:${port}`);
      const code = url.searchParams.get("code");
      if (!code) {
        res.writeHead(404);
        res.end();
        return;
      }

      res.writeHead(200, { "Content-Type": "text/html" });
      res.end("<h1>Authenticated! You can close this tab and return to the terminal.</h1>");
      server.close();

      if (url.searchParams.get("state") !== state) {
        reject(new Error("OAuth state mismatch — possible CSRF attempt."));
        return;
      }

      try {
        const tokenRes = await fetch(`${AUTH}/api/token`, {
          method: "POST",
          headers: {
            "Content-Type": "application/x-www-form-urlencoded",
            Authorization: `Basic ${basicAuth(clientId, clientSecret)}`,
          },
          body: new URLSearchParams({ grant_type: "authorization_code", code, redirect_uri: redirectUri }),
        });
        if (!tokenRes.ok) throw new Error(`Token exchange failed: ${tokenRes.status}`);
        resolve(await tokenRes.json());
      } catch (err) {
        reject(err);
      }
    });

    server.listen(port, () => {
      const params = new URLSearchParams({
        client_id: clientId,
        response_type: "code",
        redirect_uri: redirectUri,
        scope: "user-read-private playlist-modify-public playlist-modify-private",
        state,
      });
      const authUrl = `${AUTH}/authorize?${params}`;
      console.log(`\nOpening Spotify login — if the browser doesn't open, visit:\n${authUrl}\n`);
      openBrowser(authUrl);
    });

    server.on("error", reject);
  });

const apiFetch = async (path, accessToken, options = {}) => {
  const res = await fetch(`${API}${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Spotify ${options.method ?? "GET"} ${path} → ${res.status}: ${body}`);
  }
  return res.status === 204 ? null : res.json();
};

export const getMe = (accessToken) => apiFetch("/me", accessToken);

const COVER_FILTERS = ["karaoke", "made famous by", "performed by", "originally by"]
  .map((t) => `NOT "${t}"`)
  .join(" ");

export const searchTrack = async (title, artist, accessToken) => {
  // Prefer field-filtered search when we have both title and artist for precision.
  const q = artist
    ? `track:${title.substring(0, 30)} artist:${artist.substring(0, 30)} ${COVER_FILTERS}`
    : `${title.substring(0, 40)} ${COVER_FILTERS}`;

  const params = new URLSearchParams({ q, type: "track", limit: "1" });
  const data = await apiFetch(`/search?${params}`, accessToken);
  return data.tracks?.items[0] ?? null;
};

export const createPlaylist = (userId, name, accessToken) =>
  apiFetch(`/users/${userId}/playlists`, accessToken, {
    method: "POST",
    body: JSON.stringify({ name, public: true, description: "Generated by PlaylistBot" }),
  });

// Spotify limit: 100 URIs per request.
export const replacePlaylistTracks = (playlistId, uris, accessToken) =>
  apiFetch(`/playlists/${playlistId}/tracks`, accessToken, {
    method: "PUT",
    body: JSON.stringify({ uris: uris.slice(0, 100) }),
  });
